name: Suggestion
description: Request a new feature or a change to an existing one.
title: '[Suggestion] '
labels:
    - enhancement
assignees:
    - itsfelix5
body:
    - type: checkboxes
      attributes:
          label: Please confirm the following.
          options:
              - label: I have checked there is no [existing issue](https://github.com/ItsFelix5/Stfu/issues?q=is%3Aissue+label%3A%22enhancement%22) for this
                required: true
    - type: textarea
      attributes:
          label: Describe the problem
          description: A clear and concise description of what the problem is that you want fixed.
          placeholder: I am always frustrated when...
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the solution you'd like
          placeholder: A clear and concise description of how you would like it to be.
      validations:
          required: true
